import sys
import argparse
from pathlib import Path

import yaml


SCHEMA_PATH = Path(__file__).parent.parent / "schema.yaml"


def main(dry_run=False):
    here = Path(__file__).parent
    tests_dir = here.parent / "tests"
    sys.path.insert(0, str(tests_dir.resolve()))

    from schema import Bottica

    schema_dict = Bottica.schema()

    if dry_run:
        stream = sys.stdout
    else:
        stream = open(SCHEMA_PATH, "w")

    stream.writelines(
        [
            "# Generated by scripts/generate_schema.py\n",
            "# using Bottica model from tests/schema.py\n\n",
        ]
    )
    yaml.dump(schema_dict, stream=stream, Dumper=yaml.SafeDumper, width=80)

    stream.close()

    if not dry_run:
        print(f"Output schema to {SCHEMA_PATH.resolve()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate the bottica schema")
    parser.add_argument(
        "-d",
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of saving.",
    )
    args = parser.parse_args()

    main(args.dry_run)
